### PR TITLE
Ghost Full Chain

### PR DESCRIPTION
**Pull request by Temigo**
Implementation of deghosting chain

### CODE REVIEW

**Comment by Temigo** [comment]
I am fixing the tests.

**Comment by Temigo** [comment]
I think I have exhausted ideas for now.  Travis fails with 2 errors: `AttributeError: type object 'ParticleImageClassifier' has no attribute 'MODULES'` and same for `FullChain` model from `full_chain_5.py`. Both of these models have the attribute `MODULES`, you can check in the [code](https://github.com/Temigo/lartpc_mlreco3d/blob/temigo/mlreco/models/particle_types.py#L11).

 The command `pytest` runs fine on my computer (with same Python + PyTest versions).

```
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.6.9, pytest-5.3.1, py-1.8.0, pluggy-0.13.1                                                                                                             
rootdir: /u/ki/ldomine/lartpc_mlreco3d/test, inifile: pytest.ini                                                                     
plugins: dash-1.6.1                                                                                                                    
collected 112 items                                                                                                                                                              
                                                                                                                                       
test_collate.py ....                                                                                                                                                       [  3%]
test_loader.py ..                                                                                                                                                          [  5%]
test_parser.py .........                                                                                                                                                   [ 13%]
test_sampler.py ..                                                                                                                                                         [ 15%]
test_unwrapper.py ..                                                                                                                                                       [ 16%]
test_models/test_models_basic.py ....................x..........                                                                                                           [ 44%]
test_models/test_models_forward.py s..sssssssssssssssssxssssssssss                                                                                                         [ 72%]
test_models/test_models_full.py s..sssssssssssssssssxssssssssss                                                                                                            [100%]
               
```

To compare with the output on TravisCI:

```
============================= test session starts ==============================

platform linux -- Python 3.6.9, pytest-5.3.1, py-1.8.0, pluggy-0.13.1

rootdir: /app/lartpc_mlreco3d/test, inifile: pytest.ini

plugins: dash-1.7.0

collected 92 items

app/lartpc_mlreco3d/test/test_collate.py ....                            [  4%]

app/lartpc_mlreco3d/test/test_loader.py ss                               [  6%]

app/lartpc_mlreco3d/test/test_parser.py ..........                       [ 17%]

app/lartpc_mlreco3d/test/test_sampler.py ..                              [ 19%]

app/lartpc_mlreco3d/test/test_unwrapper.py ..                            [ 21%]

app/lartpc_mlreco3d/test/test_models/test_models_basic.py .............. [ 36%]

......xE.E                                                               [ 47%]

app/lartpc_mlreco3d/test/test_models/test_models_forward.py s...ssssssss [ 60%]

ssssssssxEsE                                                             [ 73%]

app/lartpc_mlreco3d/test/test_models/test_models_full.py s...sssssssssss [ 90%]

sssssxEsE                                                                [100%]


```

Suggestions welcome...!

**Comment by drinkingkazu** [comment]
Have you tried running the exact command same as Travis (docker command)?
`docker run --mount type=bind,source=$PWD/lartpc_mlreco3d,target=/app/lartpc_mlreco3d deeplearnphysics/larcv2:ub18.04-gpu-ana0-ml-larcv2 pytest /app/lartpc_mlreco3d/test`

**Comment by Temigo** [comment]
Thanks for the idea! I just tried this exact command and it still works fine for me.

```
============================= test session starts ==============================                                       
platform linux -- Python 3.6.9, pytest-5.3.1, py-1.8.0, pluggy-0.13.1                                                       
rootdir: /app/lartpc_mlreco3d/test, inifile: pytest.ini                                                                            
plugins: dash-1.7.0                                                                                                              
collected 112 items                                                                                                              
                                                                                                                                
app/lartpc_mlreco3d/test/test_collate.py ....                            [  3%]                                             
app/lartpc_mlreco3d/test/test_loader.py ss                               [  5%]                                               
app/lartpc_mlreco3d/test/test_parser.py .........                        [ 13%]                                                 
app/lartpc_mlreco3d/test/test_sampler.py ..                              [ 15%]                                                                         
app/lartpc_mlreco3d/test/test_unwrapper.py ..                            [ 16%]                                               
app/lartpc_mlreco3d/test/test_models/test_models_basic.py .............. [ 29%]                                                   
......x..........                                                        [ 44%]                                                     
app/lartpc_mlreco3d/test/test_models/test_models_forward.py s..sssssssss [ 55%]                                                    
ssssssssxssssssssss                                                      [ 72%]                                                   
app/lartpc_mlreco3d/test/test_models/test_models_full.py s..ssssssssssss [ 85%]                                                
sssssxssssssssss                                                         [100%]                                       
      
```

**Comment by Temigo** [comment]
One thing I noticed is that my (successful) runs say `collected 112 items  ` but the ones on Travis CI say `collected 92 items`. It sounds to me almost as if we were not using the same code version...

**Comment by drinkingkazu** [comment]
Interesting: could we make this explicit by printing out the code revision within pytest? If you could test that locally to confirm, then we should see pytest log from travis to see if that shows up...

**Pull request merged**
